name: Check Dependencies

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '34 10 * * 5'

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Create new package-lock.json
        run: npm install

      - name: Do Quick Install
        run: npm ci

      - name: Check for vulnerable dependencies
        run: npm audit --audit-level=high
